import { IJourney } from "@/interfaces/index";

export const FerasatEducation: IJourney.Education[] = [
  {
    degree: "Matric",
    studyIn: "Science",
    duration: "01/2010 - 03/2018",
    institutionName: "Laural Bank Public School (LPS)",
    marks: "",
    animation: "animation-1",
  },
  {
    degree: "Intermediate",
    studyIn: "Science",
    duration: "01/2018 - 03/2019",
    institutionName: "Punjab Group of Colleges (PGC)",
    marks: "",
    animation: "animation-2",
  },
  {
    degree: "Bachelors",
    studyIn: "Computer Science",
    duration: "08/2019 - 08/2023",
    institutionName: "Univeristy of Central Punjab (UCP)",
    marks: "CGPA: 3.4",
    animation: "animation-3",
  },
];

export const FerasatSkills: string[] = [
  "JavaScript",
  "Node.js",
  "Vue.js",
  "C++",
  "Vuex",
  "TypeScript",
  "Laravel",
  "Python",
  "Pinia",
  "Express.js",
  "MongoDB",
  "MySQL",
  "HTML",
  "Sequelize",
  "CSS",
  "Sass",
  "TailwindCSS",
  "Bootstrap",
  "Vuetify",
  "Git",
  "GitHub",
  "NPM",
  "Composer",
  "VS Code",
  "PyCharm",
  "Postman",
  "Svelte",
  // "React",
  // "Next.js",
  // "Nuxt.js",
  // "Angular",
  // "Django",
  // "Flask",
  // "Java",
  // "C#",
  "PHP",
  "C",
];

export const FerasatInterests: string[] = [
  "Cricket",
  "Reading",
  "Coding",
  "Netflix",
];
