import { IProjects } from "@/interfaces/index";

export const FerasatProjects: IProjects.PersonalProjectsPayload[] = [
  {
    title: "NRTS",
    subtitle: "Final Year Project",
    date: "08/2022 - 17-2023",
    content: [
      "Integrate Recruitment portal for Hiring candidates",
      "Technologies: NodeJs, VueJs, Javascript, Google API, Express Js",
      "Work on Database and API's Integration",
      "Work on Backend and Frontend of the project.",
    ],
    links: [
      {
        name: "NRTS- Frontend",
        color: "leadership-management",
        url: "",
      },
      {
        name: "NRTS- Backend",
        color: "link",
        url: "",
      },
    ],
    animation: "animation-1",
    projectImages: [
      "../src/assets/images/projectImages/n1.jpg",
      "../src/assets/images/projectImages/n2.png",
      "../src/assets/images/projectImages/n3.png",
      "../src/assets/images/projectImages/nrts.png",
      "../src/assets/images/projectImages/nrts3.png",
      "../src/assets/images/projectImages/nrts4.png",
      "../src/assets/images/projectImages/nrts5.png",
      "../src/assets/images/projectImages/nrts6.png",
      "../src/assets/images/projectImages/nrts7.png",
      "../src/assets/images/projectImages/n4.png",
      "../src/assets/images/projectImages/n5.png",
      "../src/assets/images/projectImages/n5.png",
      "../src/assets/images/projectImages/n6.png",
      "../src/assets/images/projectImages/n7.png",
    ],
    selected: false,
  },
  {
    title: "The95Star",
    subtitle: "",
    date: "03/2022 - 07-2023",
    content: [
      "Application used for Online Booking of cars",
      "Technologies: NodeJs, VueJs, Javascript, Google API, Express Js",
      "Work on Database and API's Integration",
      "Work on Backend and Frontend of the project.",
    ],
    links: [
      {
        name: "the95Star.com",
        color: "leadership-management",
        url: "https://the95star.com/",
      },
    ],
    animation: "animation-2",
    projectImages: [
      "../src/assets/images/projectImages/s4.png",
      "../src/assets/images/projectImages/s5.png",
      "../src/assets/images/projectImages/s2.png",
      "../src/assets/images/projectImages/s3.png",
      "../src/assets/images/projectImages/s1.png",
    ],
    selected: false,
  },
  {
    title: "HCMS",
    subtitle: "",
    date: "07/2023 - Present",
    content: [
      "HCMS is the Human Capital Mangement System",
      "Technologies: NodeJs, VueJs, TypeScript, Google API, Express Js, PostGre SQL",
      "Integrate Design and Structure for hcms.ai recruitment portal",
      "Integrate Chat Bot for the recruitment portal",
      "Working as a Frontend Developer",
    ],
    links: [
      {
        name: "Recruitment Hcms.Ai",
        color: "leadership-management",
        url: "https://recruitment.hcms.ai/",
      },
    ],
    animation: "animation-3",
    projectImages: [
      "../src/assets/images/projectImages/HCMS1.png",
      "../src/assets/images/projectImages/HCMS2.png",
      "../src/assets/images/projectImages/HCMS3.png",
      "../src/assets/images/projectImages/HCMS4.png",
      "../src/assets/images/projectImages/HCMS5.png",
      "../src/assets/images/projectImages/HCMS6.png",
      "../src/assets/images/projectImages/HCMS7.png",
    ],
    selected: false,
  },
  {
    title: "QudraTech.AI Portal",
    subtitle: "HCMS",
    date: "07/2023 - Present",
    content: [
      "An AI upskilling journey ending with a job.",
      "Technologies: Vue2, TypeScript, Axios, Vuetify, PostGre SQL, NodeJs, Express Js",
      "Work on the Inception bot test integration",
      "Implement the Structure and Design for the Inception Recruitment Portal",
    ],
    links: [
      {
        name: "QudraTech AI",
        color: "leadership-management",
        url: "https://www.qudra-tech.ai/auth/dashboard",
      },
    ],
    animation: "animation-5",
    projectImages: [
      "../src/assets/images/projectImages/I1.png",
      "../src/assets/images/projectImages/I2.png",
      "../src/assets/images/projectImages/I3.png",
      "../src/assets/images/projectImages/I4.png",
    ],
    selected: false,
  },
  {
    title: "HCMS Landing Page",
    subtitle: "",
    date: "07/2023 - Present",
    content: [
      "Application Empowering the Future of Human Capital Management",
      "Technologies: Vue3, TypeScript, Axios, Vuetify, GSAP Animation",
      "Work on Integration of whole landing page structure",
      "Designs and Animations Integration",
      "Integrate Chat Bot for the HCMS.AI",
    ],
    links: [
      {
        name: "Hcms Landing Page",
        color: "leadership-management",
        url: "https://hcms.ai/",
      },
    ],
    animation: "animation-6",
    projectImages: [
      "../src/assets/images/projectImages/LandingPage1.png",
      "../src/assets/images/projectImages/LandingPage2.png",
      "../src/assets/images/projectImages/LandingPage3.png",
      "../src/assets/images/projectImages/LandingPage4.png",
      "../src/assets/images/projectImages/LandingPage5.png",
      "../src/assets/images/projectImages/LandingPage6.png",
      "../src/assets/images/projectImages/LandingPage7.png",
    ],
    selected: false,
  },
  {
    title: "ESE",
    subtitle: "HCMS",
    date: "07/2023 - Present",
    content: [
      "Empowering Education, Elevating Careers. Your Bridge to Future Success!",
      "Technologies: Vue2, TypeScript, Axios, Vuetify, PostGre SQL, NodeJs, Express Js",
      "Implement the Teacher, Student and Administration Signup process by bot",
    ],
    links: [
      {
        name: "ESE Portal",
        color: "leadership-management",
        url: "https://ese.hcms.ai/auth/dashboard",
      },
    ],
    animation: "animation-4",
    projectImages: [
      "../src/assets/images/projectImages/ESE.png",
      "../src/assets/images/projectImages/ESE1.png",
      "../src/assets/images/projectImages/ESE2.png",
      "../src/assets/images/projectImages/ESE3.png",
      "../src/assets/images/projectImages/ESE4.png",
    ],
    selected: false,
  },
  {
    title: "Education Portal",
    subtitle: "HCMS",
    date: "07/2023 - Present",
    content: [
      "Technologies: Vue2, TypeScript, Axios, Vuetify, PostGre SQL, NodeJs, Express Js",
      "Implement the design and structure for recruitment process",
      "Integarte the process of applying for the job and give the test",
    ],
    links: [
      {
        name: "ESE Portal",
        color: "leadership-management",
        url: "https://edu.hcms.ai/auth/dashboard",
      },
    ],
    animation: "animation-2",
    projectImages: [
      "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
      "https://cdn.vuetifyjs.com/images/cards/hotel.jpg",
      "https://cdn.vuetifyjs.com/images/cards/sunshine.jpg",
    ],
    selected: false,
  },
  {
    title: "Hiring Portal",
    subtitle: "HCMS",
    date: "07/2023 - Present",
    content: [
      "Technologies: Vue2, TypeScript, Axios, Vuetify, PostGre SQL, NodeJs, Express Js",
      "Integrate the process to onboard the candidate",
      "Integrate the process for Hiring Manager to create the job and post it",
      "Integrate the process for Hiring Manager to manage the recruiter and candidate",
    ],
    links: [
      {
        name: "Hiring Portal",
        color: "leadership-management",
        url: "https://hiring.hcms.ai/",
      },
    ],
    animation: "animation-2",
    projectImages: [
      "https://cdn.vuetifyjs.com/images/cards/docks.jpg",
      "https://cdn.vuetifyjs.com/images/cards/hotel.jpg",
      "https://cdn.vuetifyjs.com/images/cards/sunshine.jpg",
    ],
    selected: false,
  },
];
